/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        corPrincipal: "#232C33",
        corSecundaria: "#46535E",
        corAoCliqueFooter: "#FFFFFF",
        corSemCliqueFooter: "#ADAFBB",
        borderFoto: "#4D5E6B",
        escritaNormal: "#E3DEDE",
        botaonNormal: "#3D50DF",
        termosUso: "#5259FD",
        registate: "#060518",
        tituloAzulBotaoContrario: "#120D26",
        cancelar: "#F93A3A",
        formsBrancas: "#E4DFDF",
      },
      fontFamily: {
        'sfdisplay': ['SFDisplay'],
        'sfdisplay-black': ['SFDisplayBlack'],
        'sfdisplay-blackitalic': ['SFDisplayBlackItalic'],
        'sfdisplay-bold': ['SFDisplayBold'],
        'sfdisplay-bolditalic': ['SFDisplayBoldItalic'],
        'sfdisplay-heavy': ['SFDisplayHeavy'],
        'sfdisplay-heavyitalic': ['SFDisplayHeavyItalic'],
        'sfdisplay-italic': ['SFDisplayItalic'],
        'sfdisplay-light': ['SFDisplayLight'],
        'sfdisplay-lightitalic': ['SFDisplayLightItalic'],
        'sfdisplay-medium': ['SFDisplayMedium'],
        'sfdisplay-mediumitalic': ['SFDisplayMediumItalic'],
        'sfdisplay-semibold': ['SFDisplaySemibold'],
        'sfdisplay-semibolditalic': ['SFDisplaySemiboldItalic'],
        'sfdisplay-thin': ['SFDisplayThin'],
        'sfdisplay-thinitalic': ['SFDisplayThinItalic'],
        'sfdisplay-ultralight': ['SFDisplayUltralight'],
        'sfdisplay-ultralightitalic': ['SFDisplayUltralightItalic'],
        'sfpro-bold': ['SFProBold'],
        'sfpro-bolditalic': ['SFProBoldItalic'],
        'sfpro-heavy': ['SFProHeavy'],
        'sfpro-heavyitalic': ['SFProHeavyItalic'],
        'sfpro-light': ['SFProLight'],
        'sfpro-semibolditalic': ['SFProSemiboldItalic'],
        'sfregular-text': ['SFRegularText'],
        'sfregular-textitalic': ['SFRegularTextItalic'],
        'sfregular-textlightitalic': ['SFRegularTextLightItalic'],
        'sfregular-textmedium': ['SFRegularTextMedium'],
        'sfregular-textmediumitalic': ['SFRegularTextMediumItalic'],
        'sfregular-text-semibold': ['SFRegularTextSemibold'],
      },
      keyframes: {
        ripple: {
          "0%": { width: "0px", height: "0px", opacity: 0.5 },
          "100%": { width: "500px", height: "500px", opacity: 0 },
        },
      },
      animation: {
        ripple: "ripple 1s linear infinite",
      },
    },
  },
  plugins: [],
};
